services:
  postgres:
    image: postgres:13
    container_name: aquamanager-db
    environment:
      POSTGRES_DB: aquamanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - aquamanager-network

  redis:
    image: redis:7-alpine
    container_name: aquamanager-redis
    ports:
      - "6379:6379"
    networks:
      - aquamanager-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: aquamanager-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aquamanager.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - aquamanager-network

volumes:
  postgres_data:

networks:
  aquamanager-network:
    driver: bridge
